import type { Trace } from '../types.js'

/** Human report without introducing an arbitrary reliability score. */
export function renderText(trace: Trace): string {
  const m = trace.summary
  return [`Session Reliability Report`, `Session: ${trace.session.id}`, `Status: ${m.completion_status}`, `Turns: ${m.turn_count} | Steps: ${m.step_count} | Model requests (settled): ${m.model_request_count}`, `Tool calls: ${m.tool_call_count} | Successes: ${m.tool_success_count} | Failures: ${m.tool_failure_count} | Cancelled: ${m.tool_cancelled_count}`, `Session duration: ${m.session_duration_ms ?? 'unavailable'} ms`, `Integrity: ${trace.integrity.truncated || trace.integrity.sequence_gaps.length ? 'INCOMPLETE' : 'complete captured prefix'}`, '', 'Detected Issues:', ...trace.findings.map(f => `- ${f.failure_type} [${f.severity}] ${f.message} (seq ${f.evidence_event_seqs.join(', ')})`), ...(trace.findings.length ? [] : ['- None detected']), '', 'Timeline:', ...trace.observations.map(e => `${e.seq.toString().padStart(4)}  ${e.type}${e.tool_name ? ` ${e.tool_name}` : ''}${e.call_id ? ` #${e.call_id}` : ''}${e.status ? ` [${e.status}]` : ''}`)].join('\n') + '\n'
}
function escape(value: unknown): string { return String(value).replace(/[&<>"']/gu, s => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[s]!) }

/** Static, offline dashboard: no scripts, remote assets or executable captured markup. */
export function renderHtml(trace: Trace): string {
  const cards = [['Turns', trace.summary.turn_count], ['Steps', trace.summary.step_count], ['Tool calls', trace.summary.tool_call_count], ['Tool failures', trace.summary.tool_failure_count], ['Findings', trace.findings.length]]
  return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src 'none'; base-uri 'none'; form-action 'none'"><title>Session Reliability Report</title><style>body{font:15px system-ui;background:#0c1525;color:#e3ebf9;max-width:1100px;margin:40px auto;padding:20px}h1{font-size:36px}h2{margin-top:32px;color:#93c5fd}.cards{display:flex;flex-wrap:wrap;gap:12px}.card{background:#17253c;padding:20px;min-width:120px;border-radius:10px}.card b{display:block;font-size:28px;margin-top:8px}table{width:100%;border-collapse:collapse}td,th{text-align:left;border-bottom:1px solid #2c3c55;padding:10px}code,pre{white-space:pre-wrap;overflow-wrap:anywhere}summary{cursor:pointer}.warning{color:#fbbf24}</style><header><p>Community plugin for DeepSeek Harness · local-first</p><h1>Session Reliability Report</h1><p><code>${escape(trace.session.id)}</code> · ${escape(trace.summary.completion_status)}</p></header><div class="cards">${cards.map(([label, value]) => `<div class="card">${label}<b>${value}</b></div>`).join('')}</div><h2>Failure findings</h2>${trace.findings.length ? trace.findings.map(f => `<p class="warning"><b>${escape(f.failure_type)} · ${escape(f.severity)}</b> ${escape(f.message)} <code>seq ${f.evidence_event_seqs.join(', ')}</code></p>`).join('') : '<p>None detected.</p>'}<h2>Turns and steps</h2>${trace.turns.map(t => `<details open><summary>Turn ${t.turn} · ${escape(t.outcome ?? 'open')}</summary>${t.steps.map(s => `<p>Step ${s.step} · ${s.assistant.length} settled model attempts · ${s.tool_calls.length} tool calls</p>`).join('')}</details>`).join('')}<h2>Timeline</h2><table><thead><tr><th>Seq</th><th>Event</th><th>Turn / Step</th><th>Call / Status</th></tr></thead><tbody>${trace.observations.map(e => `<tr><td>${e.seq}</td><td>${escape(e.type)}</td><td>${e.turn ?? '–'} / ${e.step ?? '–'}</td><td>${escape([e.tool_name, e.call_id, e.status].filter(Boolean).join(' · '))}${e.payload?.content !== undefined ? `<details><summary>Redacted content</summary><pre>${escape(JSON.stringify(e.payload.content, null, 2))}</pre></details>` : ''}</td></tr>`).join('')}</tbody></table><h2>Metrics and integrity</h2><pre>${escape(JSON.stringify({ metrics: trace.summary, integrity: trace.integrity, privacy: trace.privacy }, null, 2))}</pre><footer><p>No telemetry is sent by this plugin. Findings describe observable patterns, not task correctness.</p></footer></html>\n`
}
